### ISSUE TITLE
Add a unique_id so that icons can be changed in Home Assistant

### ISSUE THREAD

**Issue by maxshcherbina** [Mr-Groch/HA-Emulated-Color-Temp-Light#1]
I would love to be able to specify a unique_id so that we can adjust icons and names within the HASS UI. Is this possible?

**Comment by Mr-Groch** [comment]
It would be hard to specify unique_id from integration,  because this integration doesn't communicate with physical device, so it can't read its attributes like SN or MAC that is commonly used as unique_id. This integration acts more like template. Try to add unique_id manually by adding in four configuration:

```
light:
  - platform: emulated_color_temp
    name: Your new light name
    unique_id: unique_light_id
    entity_id: light.original_light_entity
```

**Comment by maxshcherbina** [comment]
Unfortunately, adding this line gives me the following warnings:
`Invalid config for [light.emulated_color_temp]: [unique_id] is an invalid option for [light.emulated_color_temp]. Check: light.emulated_color_temp->unique_id. `


My config:

```yaml
light:
  - platform: emulated_color_temp
    name: Bathroom Light (Adjusted)
    unique_id: bathroom_light_adjusted
    entity_id: light.color_temperature_light_7
    offset: -100
```
