### ISSUE TITLE
Adding Color Temperatrue to Tradfri Bulbs removes Color Wheel in UI

### ISSUE THREAD

**Issue by KuotenoAshiato** [Mr-Groch/HA-Emulated-Color-Temp-Light#2]
When integrating this Integration, the added Lamps lost the functunality to set their normal Color apart from the Temperature. So in order to be able to access both Colormodes i need to add both instances of one lamp to the UI.
I was thinking there might be a misunderstanding on my side regarding the integration, but the screenshots suggest that both modes should be selectable. Are there any files or settings that i could share to help with a further bugfix?
Developersettings show the Emulated Light with 42 Supported Features compared to 40 on the non-emulated version.

**Comment by KuotenoAshiato** [comment]
Also the brightness isn't shown correctly after turning on a lamp, but i don't see that beeing be a dealbreaker for anyone.

**Comment by Mr-Groch** [comment]
I've checked Emulated Color Temp 0.1.5 with HA 2022.2.0 and it's still working fine.

With what light (integration) do you try to use this integration? Can you check HA logs if there is any problem initilizing this integration? Can you also post your configuration?

**Comment by aetha** [comment]
I’m getting this exact same issue, running Home Assistant 2022.6.6, and Emulated Color Temp 0.1.6.

Config:
```
light:
  - platform: emulated_color_temp
    name: Dining room lamp 1
    entity_id: light.dining_room_lamp_1_hs
    offset: "-100"
  - platform: emulated_color_temp
    name: Lounge room lamp 2
    entity_id: light.lounge_room_lamp_2_hs
    offset: "-100"
```

Only thing I could find in the log:
``
2022-06-22 20:18:31 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for emulated_color_temp using this method at custom_components/emulated_color_temp/light.py, line 70: registry = await hass.helpers.entity_registry.async_get_registry()
``

I can also see this issue in the attributes:
![632874A1-E0D7-4E0E-BAF9-A7E5E2573624](https://user-images.githubusercontent.com/3007450/175010431-c14cc86c-5285-4a3c-b422-0dd934c611a9.jpeg)
